---
- name: restart jenkins
  service:
    name: jenkins
    state: restarted

- name: reload daemon
  command: systemctl daemon-reload

- name: restart jenkins
  service:
    name: jenkins
    state: restarted

