---
- name: Install Java (required for Jenkins)
  apt:
    name: openjdk-11-jdk
    state: present
  become: yes

- name: Add Jenkins repository key
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins.io.key
    state: present
  become: yes

- name: Add Jenkins repository
  template:
    src: jenkins.repo.j2
    dest: /etc/apt/sources.list.d/jenkins.list
  notify: reload daemon
  become: yes

- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
  notify: restart jenkins
  become: yes

- name: Ensure Jenkins is started & enabled
  service:
    name: jenkins
    state: started
    enabled: yes
  become: yes

