---
- name: Install Jenkins plugins
  jenkins_plugin:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - workflow-aggregator
    - docker-plugin
    - credentials
    - configuration-as-code
  notify: restart jenkins

